# Generated by Django 3.2.4 on 2022-01-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount_price',
        ),
    ]
