# Generated by Django 3.2.4 on 2022-01-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='search_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
