# Generated by Django 3.2.4 on 2022-01-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
    ]
