# Generated by Django 3.2.4 on 2022-01-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_featuredproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
