# Generated by Django 4.0.1 on 2022-02-05 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.ManyToManyField(related_name='product_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
    ]
