# Generated by Django 4.0.1 on 2022-02-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_order_shippingaddress_orderid'),
        ('myorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.shippingaddress'),
        ),
    ]
