# Generated by Django 3.2.4 on 2022-01-14 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20220114_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('phone_verified', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('default_User_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.default_user_address')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
