# Generated by Django 3.2.4 on 2022-01-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='default_User_Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.default_user_address'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
