# Generated by Django 4.0.1 on 2022-01-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_shippingaddress_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='orderid',
        ),
    ]
