# Generated by Django 3.2.4 on 2022-01-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
