# Generated by Django 4.0.1 on 2022-01-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_complete_order_payment_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_complete',
            new_name='complete',
        ),
    ]
