# Generated by Django 4.0.1 on 2022-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_transaction_id_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
