# Generated by Django 4.0.1 on 2022-02-03 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('deliveredDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
