# Generated by Django 4.0.1 on 2022-02-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_delivery_delivereddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveredDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
