# Generated by Django 4.0.1 on 2022-02-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
