# Generated by Django 4.2.1 on 2023-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_delete_myorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
