# Generated by Django 4.2.1 on 2023-08-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_orderitem_encrypted_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="encrypted_product_name",
            new_name="encrypted_product",
        ),
    ]
