# Generated by Django 4.2.1 on 2023-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0018_rename_encrypted_product_name_orderitem_encrypted_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="encrypted_product",
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
